### ISSUE TITLE
Hitsound Copier removes manual breaks on target beatmap

### ISSUE THREAD

**Issue by ekisu** [OliBomby/Mapping_Tools#101]
Sample beatmaps:
[samples.zip](https://github.com/OliBomby/Mapping_Tools/files/4775125/samples.zip)

After copying the hitsounds from [hs], the break times disappear. Looking at the .osu files, it seems they're just changed into 0 length breaks:

Before copying the hitsounds:
```ini
[Events]
//Background and Video events
0,0,"pink and blue.jpg",0,0
//Break Periods
2,16485,18378
2,49087,50215
2,107250,110827
2,117658,118786
2,164648,169602
2,176434,177562
2,179954,184908
```

After copying the hitsounds:
```ini
[Events]
//Background and Video events
0,0,"pink and blue.jpg"
//Break Periods
2,16485,16485
2,49087,49087
2,107250,107250
2,117658,117658
2,164648,164648
2,176434,176434
2,179954,179954
```

**Comment by OliBomby** [comment]
Sorry for the late response. I will look into this ASAP
