### ISSUE TITLE
Hitsound Copier doesnt correctly copy timingpoint-offsets

### ISSUE THREAD

**Issue by MaxKruse** [OliBomby/Mapping_Tools#102]
Hello,

as an example in this map: https://osu.ppy.sh/beatmapsets/1118708/discussion/2353407/general#/1656469

the hs diff has all timingpoints correctly alligned. When using Hitsound Copier on all remainding diffs, the offset of some timing points (AiMod only finds the kiai's) is off because of rounding erros either on osu-side or this program.

**Comment by OliBomby** [comment]
Sorry for the slow response. I will look into this ASAP

**Comment by OliBomby** [comment]
I investigated and it weems like user error. The timingpoint copying has a 2 milliseconds leniency, so it just overwrote the 1ms off timingpoint in your target diff. Without the leniency it would put a new greenline on the exact time of the hs diff and result in two greenlines 1ms next to eachother. I also can't just move the offsets of the greenlines in the target diff without the risk of changing SV when the hs diff has unsnapped timingpoints.

I suggest you just use Map Cleaner to resnap your greenlines before or after the copying.
