### ISSUE TITLE
Timing Helper doesn't work with maps having no red lines

### ISSUE THREAD

**Issue by ciiii0001** [OliBomby/Mapping_Tools#106]
How to reproduce:
1. Open a map with no red lines but have some bookmarks in the editor
2. Mapping tools----File----Open current beatmap
3. Timing helper----Run
4. Getting this error (序列不包含任何元素=sequence contains no elements; 在=at)
![error](https://user-images.githubusercontent.com/66686071/88838559-51adb300-d20c-11ea-996b-2b48414627cf.PNG)

**Comment by OliBomby** [comment]
Usually Timing Helper uses the existing timing to determine the number of between between each marker, so it's usefull to have a bpm which is already roughly correct. I guess I can fix this issue by just having a default bpm it uses if there are no redlines.
