### ISSUE TITLE
Tiny idea of making combo color studio more convenient to use

### ISSUE THREAD

**Issue by Ryuusei-Aika** [OliBomby/Mapping_Tools#116]
When I try to copy a timestamp from osu! (stable) to the "offset" column of combo color studio, it is in a form with a hyphen (like 00:00:015 - ) while  the combo color studio will warn that "not available to convert 00:00:015 - " (I am not using an English OS so the warning is also not in English, but it should have the similar meaning) which requires a manual removal of the hyphen, and that causes a little bit nuisance to me.

I think it would be great if you can implement a little function that automatically remove the hyphen (and the space before it, of course) from the copied timestamp from osu!, that would make the colorhax work more convenient.

**Comment by OliBomby** [comment]
Thanks for pointing this out to me. I thought it would work with the hyphen but apparently not. I will fix this.
For now you can still use it semi-conveniently by copying the timestamp from osu! by clicking on the time indicator at the bottom left of the editor. That will give you a timestamp without a hyphen.

**Comment by OliBomby** [comment]
fixed in latest commit
