### ISSUE TITLE
Opening/browsing beatmap selecting wrong hard drive

### ISSUE THREAD

**Issue by Xzeni** [OliBomby/Mapping_Tools#133]
Pretty self explanatory.

I have my osu! on my D: Drive but opening the current beatmap will default it as C: Drive, causing things like Hitsound Copier to fetch a non-existent file. It also messes with the default location when browsing the drive.

Do note that the rest of the directory are correct, it's just the letter drive that's wrong.

**Comment by OliBomby** [comment]
Can you go to Option -> Preferences and check if all those paths (especially the songs folder path) are using the right drive letter. The 'Get current beatmap' feature uses that songs folder path as the start of the path to any beatmap.

**Comment by Xzeni** [comment]
Nope, using C:\osu! instead of D:\osu!, same with the rest.
I also noticed that the Backups folder doesn't use the changed installation path, which should be located in my D:\osu!\Mapping Tools. Instead, it uses the default installation path, which is at C:\Users\<User>\AppData\Local\Mapping Tools\Backups

Edit: Should also note that osu! user config file is empty and not sure if that was intended.

**Comment by OliBomby** [comment]
ok, all you need to is change the paths in the Preferences to the correct paths. You can click the folder icon to find the correct folders with the file explorer.
