### ISSUE TITLE
Autofail Detector "Get auto-fail fix guide" 

### ISSUE THREAD

**Issue by AG89** [OliBomby/Mapping_Tools#134]
![image](https://user-images.githubusercontent.com/22873716/99200453-6ab68180-2773-11eb-9b87-a2ea79ca22d9.png)

**Comment by OliBomby** [comment]
Some maps just have too much 2B so an auto-fail padding solution doesn't exist. I see you tried it on Endless Tewi-ma Park and that is one of the maps I tested on and I know that one is impossible.
This error is a problem with the map and I can't do anything more to fix it.
