### ISSUE TITLE
Proposal of adding a function to let 5% volume green lines stay unmodified while changing the volume by using the property transformer

### ISSUE THREAD

**Issue by Ryuusei-Aika** [OliBomby/Mapping_Tools#139]
quite obvious reasons i guess... not sure if there's already a function about that though maybe i am just too dumb to not noticing its existence

**Comment by OliBomby** [comment]
You can kinda already do this by transforming the volumes and then changing back the volumes which used to be 5% by using the whitelist filter.

I had planned a blacklist filter which would obviously make this a lot more straight forward, but I let it fall behind in favour of adding other features first.

I'll leave this issue open until I get a blacklist filter in Property Transformer.

**Comment by OliBomby** [comment]
blacklist filter added in 1.8.1.0 !
