### ISSUE TITLE
Feature request: Select specific sections to clean or/and improve resnaps (Map Cleaner)

### ISSUE THREAD

**Issue by IsomirDiAngelo** [OliBomby/Mapping_Tools#143]
Sometimes when you change timing on a map and want to use map cleaner to resnap everything, there's likely gonna be issues if you are using both 1/6 and 1/4 snappings because many 1/4 will be snapped 1/6 earlier/later. (Same with using other snapping divisions of course but I think those are the most common ones where everything gets messed up)

I think it could be helpful to have an option to restrict Map Cleaner to only clean certain areas so that we could operate a resnap on certain parts using only 1/4 divisor for example and isolate the parts that don't use that snapping. Those other parts won't be all over the place and we would know there's only going to be those parts that we have to resnap manually. 

Other option, I don't know if that is possible, but, for each object, take a look at the snapping used before the cleaning, and try to use that same snapping on resnap.

**Comment by OliBomby** [comment]
I see how a time filter on Map Cleaner can be usefull, so I might add it in the distant future.

For your problem specifically, you should use Timing Copier to resnap your objects when you change timing. Just make the timing changes in a seperate diff and then copy the timing to your actual diffs with the tool. It has an option to do a kind of BPM scaled resnap which will give the same result as your second suggestion.
