### ISSUE TITLE
Latest version (v1.8.6) seems having issue on showing the drop down menu

### ISSUE THREAD

**Issue by Ryuusei-Aika** [OliBomby/Mapping_Tools#147]
![image](https://user-images.githubusercontent.com/52080494/119392050-c99c1b00-bd01-11eb-8ff2-d3fbf3af7e20.png)

**Comment by OliBomby** [comment]
Can you elaborate. What is the issue? I think I noticed some weirdness myself but I couldn't reliably replicate it.

**Comment by Ryuusei-Aika** [comment]
Well, I think it's more like a UI issue from my end? The drop-down menu is covering the main menu right now (as shown in the red box below), while in the version before (and I suppose it was the "normal" UI) the drop-down menu did not cover the main menu (as shown in the green box below).

![image](https://rsak.s-ul.eu/U5njjKd7)

**Comment by OliBomby** [comment]
I see it too. This might be a side-effect of upgrading to .NET 5 WPF. I don't really know what to do about that now.

**Comment by OliBomby** [comment]
This seems to have resolved itself.
