### ISSUE TITLE
Timing Copier fails to work with irregular snaps at default settings

### ISSUE THREAD

**Issue by mcendu** [OliBomby/Mapping_Tools#149]
Per title. Adding 1/5, 1/7 and 1/9 makes it work correctly, but this is unnecessary complexity in my opinion.

**Comment by OliBomby** [comment]
I think if you want to have Timing Copier to resnap your objects to the right snaps it is necessary to tell the tool which snaps to resnap to. 1/5, 1/7, and 1/9 snaps are irregular snaps which don't get used too often so adding them as default settings doesn't make sense. If they were default that will give the issue "Timing Copier fails to work with regular snaps at default settings" as it might resnap something to 1/7 while the map only uses 1/4.
