### ISSUE TITLE
Misleading error message about missing .NET runtime

### ISSUE THREAD

**Issue by robertoesteves13** [OliBomby/Mapping_Tools#150]
The error message only says to install .NET but it doesn't say it needs to be the 32bit version. Spent 3 days figuring out why It wasn't opening even installing the 64bit version of .NET, so it should be fine to specify at the error message the 32bit version :)

**Comment by OliBomby** [comment]
I can't actually change this message that shows up when you dont have .NET installed. I think it's something done by Windows.

The real fix is to have both a x64 and x86 release of mapping tools and then hope that the users install the same version of .NET as their version of mapping tools.
Making both x64 and x86 releases of mapping tools is something i'm gonna do but it requires making changes to the auto-updater and that breaks backwards compatibility of updating a bit.

**Comment by OliBomby** [comment]
Fixed in 1.8.9. The installer now even installs .NET for you. This issue shouldn't happen for anyone anymore unless they are auto-updating from an older version for which i'll add something in the FAQ.
