### ISSUE TITLE
Feature Request: open the program in the maximized window by default

### ISSUE THREAD

**Issue by Ryuusei-Aika** [OliBomby/Mapping_Tools#151]
Windows 20H2, latest ver of MT

Currently when opening the program sometimes it would be opened in a window with extremely smaller size (like the image below) that would cause an misclick to the "close" button when trying to maximize the window.
![image](https://user-images.githubusercontent.com/52080494/122044798-82d8a700-ce0f-11eb-91c5-5eb252ad74bc.png)

So I think It would be good if the MT window can be maximized by default when opening it.

**Comment by OliBomby** [comment]
I'm aware of this issue. Something is causing the restore boundary of the window to be something really small, that is the boundary the window remembers for when you start up MT again. I will fix this by making sure this boundary is at least a certain size and visible on the monitor area.

**Comment by OliBomby** [comment]
Fixed in 1.8.9. Now the window will definitely appear on screen with at least 300 width and 100 height.
