### ISSUE TITLE
BetterSave fails when saving on dialogue prompt after reloading skin

### ISSUE THREAD

**Issue by Wrongwayscout** [OliBomby/Mapping_Tools#153]
Often when reloading my skin with ctrl+alt+shift+s (to fix display errors in the editor) and saving via the prompt that appears, BetterSave fails to overwrite the osu! save. 
The error given is that no active editor is found, so I assume that the issue is caused by how the osu window isn't in focus after clicking the dialogue. 
Clicking back on the window very quickly or tabbing back in usually makes it work, but it also sometimes works without doing anything.

**Comment by OliBomby** [comment]
I assume you are talking about the 'Override osu! save with BetterSave' feature. It detects the change to the .osu file from saving and then tries to read memory from the editor to override that save. 

If the editor gets closed right after the save, for instance when you close out the editor and choose to save, the editor can be deleted before mapping tools has the chance to read it. 

I assume that when reloading the skin it also briefly removes the editor and then creates a new instance, so at that moment mapping tools cant read the editor memory, so it doesnt work.

This is an inherent limitation of the automatic save override feature, so I can't fix this. You'll have to save with Ctrl+S or using the BetterSave hotkey before reloading the skin.
