### ISSUE TITLE
Feature request: Offset Editor

### ISSUE THREAD

**Issue by Hiviexd** [OliBomby/Mapping_Tools#156]
A tool that lets you edit the offset of every diff in a map with a single click, it should also have extra options that lets you change the offset of green lines, objects, preview point, bookmarks accordingly.

this should save mappers from the tedious task of manually changing the timing points' offset, preview point, bookmarks (if needed), objects, and repeat that for every difficulty on the set.

**Comment by OliBomby** [comment]
Property Transformer does exactly this. Just select multiple maps with 'File > Open beatmap' and then enable 'Synchronize time fields'.
