### ISSUE TITLE
Removing duplicated tags in Metadata Manager should be made optional

### ISSUE THREAD

**Issue by STCapricorn** [OliBomby/Mapping_Tools#158]
because sometimes i know what i'm doing when using them, like for example, artists that have the same first/last name, light novel titles with repeating particles, etc.

perhaps adding it as a tick box somewhere would be nice

**Comment by OliBomby** [comment]
Removing the duplicate tags in the examples you mentioned shouldn't have any effect on the search behaviour of the map.

Do you want to have duplicate tags for vanity reasons?

**Comment by STCapricorn** [comment]
uh _very_ late reply but yes basically

also this metadata allowance calls for it 
![image](https://user-images.githubusercontent.com/7162510/164193310-187f2f98-aa8c-4ba2-bc72-7bf5736638bb.png)

**Comment by OliBomby** [comment]
> uh _very_ late reply but yes basically

Fair enough, but I will regard this as extremely low priority because duplicate tags do nothing functionally and I doubt many people look at tags.
