### ISSUE TITLE
Feature Request: minimize to tray

### ISSUE THREAD

**Issue by ChenMerami** [OliBomby/Mapping_Tools#159]
would be good if it could minimize to tray and also launch on windows start, so it would automatically make backups of my maps without me having to think about it

**Comment by OliBomby** [comment]
Ok

**Comment by potoofu** [comment]
You can easily set any program to start with windows if you just put it in the startup folder. Not sure its worth adding that feature

**Comment by brickyosu** [comment]
make this alive or close it
