### ISSUE TITLE
how would i run this on a binary package for dotnet?

### ISSUE THREAD

**Issue by brickyosu** [OliBomby/Mapping_Tools#164]
I am on a school laptop so i won't have admin. I know you will say that this cannot run without dotnet but it is however possible using the dotnet binary package. do you know how to use it on a portable/binary package of dotnet? thanks!

**Comment by potoofu** [comment]
It could be possible to build it as a self-contained application as described in [here](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained).

Im not exactly sure what you are referencing with "dotnet binary package" but you should be able to run programs like so  ```dotnet.exe 'Mapping Tools.dll'``` in the command line right? This might need path or env Variables tho so idk exactly.

**Comment by brickyosu** [comment]
> It could be possible to build it as a self-contained application as described in [here](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained).
> 
> Im not exactly sure what you are referencing with "dotnet binary package" but you should be able to run programs like so `dotnet.exe 'Mapping Tools.dll'` in the command line right? This might need path or env Variables tho so idk exactly.

i dont know how to build it as a self contained app, i dont even know how to execute commands. oh yeah mapping tools dll when i drag it to the dotnet.exe it will not work

**Comment by potoofu** [comment]
Ive built and uploaded the self-contained application for x64 Windows [here](https://drive.google.com/file/d/1Fsr4sEn7fA8O3yPOToULxdHIwEhq1oYs/view?usp=sharing) if you want to test if it works.


1. If you want to build it yourself you have to first download and install the [Dotnet SDK](https://dotnet.microsoft.com/download).
2. Then you have to use the command line to [git clone](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository) the repository.
3. Finally also in the command line go into the folder that you just cloned and run this command ```dotnet publish .\Mapping_Tools\Mapping_Tools.csproj -c Release -r win-x64``` (Replace the "x64" with "x86" if your Windows is 32-Bit).

**Comment by brickyosu** [comment]
> Ive built and uploaded the self-contained application for x64 Windows [here](https://drive.google.com/file/d/1Fsr4sEn7fA8O3yPOToULxdHIwEhq1oYs/view?usp=sharing) if you want to test if it works.
> 
> 1. If you want to build it yourself you have to first download and install the [Dotnet SDK](https://dotnet.microsoft.com/download).
> 2. Then you have to use the command line to [git clone](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository) the repository.
> 3. Finally also in the command line go into the folder that you just cloned and run this command `dotnet publish .\Mapping_Tools\Mapping_Tools.csproj -c Release -r win-x64` (Replace the "x64" with "x86" if your Windows is 32-Bit).

Thank you. By the way, if you want me to correct a word, it's "I've" instead of "Ive". but all jokes aside, thanks for the help!
