### ISSUE TITLE
.. a new error?

### ISSUE THREAD

**Issue by brickyosu** [OliBomby/Mapping_Tools#165]
From the title, whenever I load a current beatmap, the difficulty name is chinese/japanese/symbols. Please help!

**Comment by OliBomby** [comment]
What version of mapping tools do you use? What version of osu! do you use? Cutting edge or stable? What operating system do you use? Does the problem persist after a pc restart? Is the result the same when looking inside the osu! editor vs when in song select?

**Comment by brickyosu** [comment]
> What version of mapping tools do you use? What version of osu! do you use? Cutting edge or stable? What operating system do you use? Does the problem persist after a pc restart? Is the result the same when looking inside the osu! editor vs when in song select?

the most recent version, b20211122.1, idk maybe stable, windows, not tried restarting yet ill give an update, idk what that means but i think the result is the same.

edit: please respond fast because I have alot of school and i really wanna sliderate some sliders today

**Comment by brickyosu** [comment]
oh yeah i dotnet build mapping tools

**Comment by OliBomby** [comment]
It should work properly for this version of osu! Try restarting pc because that is the only known fix

**Comment by brickyosu** [comment]
> It should work properly for this version of osu! Try restarting pc because that is the only known fix

sadly it does not work

**Comment by brickyosu** [comment]
please respond asap, it has been 3 days

if you're busy then wait till you are not?

**Comment by OliBomby** [comment]
I dont have a solution for your problem, because I don't know why it does this and I can't recreate the issue on my end. I can talk with Karoo about the issue maybe he knows more. It would help if you showed an example of the issue.

By the way you can still use all of mapping tools without editor reader. Even if this feature doesnt work you can still select a beatmap with the browse option and import a slider with the time selection mode.

**Comment by Karoo13** [comment]
You don't have the latest version of mapping tools or at least EditorReader.dll, update it. https://github.com/Karoo13/EditorReader/blob/master/EditorReader.dll

**Comment by brickyosu** [comment]
> You don't have the latest version of mapping tools or at least EditorReader.dll, update it. https://github.com/Karoo13/EditorReader/blob/master/EditorReader.dll

nope, doesn't work

**Comment by brickyosu** [comment]
> I dont have a solution for your problem, because I don't know why it does this and I can't recreate the issue on my end. I can talk with Karoo about the issue maybe he knows more. It would help if you showed an example of the issue.
> 
> By the way you can still use all of mapping tools without editor reader. Even if this feature doesnt work you can still select a beatmap with the browse option and import a slider with the time selection mode.

using the manual beatmap select, it works but when i use a tool the diff becomes random symbols

**Comment by OliBomby** [comment]
You say the diff name becomes random symbols is this in the current beatmap path of mapping tools or in the actual beatmap you just edited? I think I misinterpreted your problem since you provide so little information. Please add a screenshot and video of the problem.

Can you go to About > About and tell us what the version number what you see there is.

Try going to the Preferences and uncheck the box that says "Use editor reader". See if the problem persists after that.

**Comment by brickyosu** [comment]
> You say the diff name becomes random symbols is this in the current beatmap path of mapping tools or in the actual beatmap you just edited? I think I misinterpreted your problem since you provide so little information. Please add a screenshot and video of the problem.
> 
> Can you go to About > About and tell us what the version number what you see there is.
> 
> Try going to the Preferences and uncheck the box that says "Use editor reader". See if the problem persists after that.

k

**Comment by brickyosu** [comment]
https://user-images.githubusercontent.com/85379324/146096967-2835b5d9-1383-407b-8308-21490a6dea10.mp4

I found a new error, also i tried anything that you guys wanted me to do to fix this

**Comment by Karoo13** [comment]
The first thing we told you to do was to tell us what version of mapping tools you are using, and then we told you to update it. At 1:19 in the video it says you are on 1.8.12 which is too old a version for this to work. You failed to update mapping tools correctly. I would suggest removing it and doing a fresh install.

I see the problem, the master branch is out of date, use dev.

**Comment by brickyosu** [comment]
> The first thing we told you to do was to tell us what version of mapping tools you are using, and then we told you to update it. At 1:19 in the video it says you are on 1.8.12 which is too old a version for this to work. You failed to update mapping tools correctly. I would suggest removing it and doing a fresh install.
> 
> I see the problem, the master branch is out of date, use dev.

thx

**Comment by brickyosu** [comment]
> The first thing we told you to do was to tell us what version of mapping tools you are using, and then we told you to update it. At 1:19 in the video it says you are on 1.8.12 which is too old a version for this to work. You failed to update mapping tools correctly. I would suggest removing it and doing a fresh install.
> 
> I see the problem, the master branch is out of date, use dev.

?

https://user-images.githubusercontent.com/85379324/146312067-af1f928f-9177-4bd5-8e63-91d363e2666b.mp4

**Comment by brickyosu** [comment]
i think i need to make a new post
