### ISSUE TITLE
"Y O U R E D I T O R D O E S N O T E X I S T" error?

### ISSUE THREAD

**Issue by brickyosu** [OliBomby/Mapping_Tools#166]
https://user-images.githubusercontent.com/85379324/146312596-191dc8f2-638b-417c-ab3a-db9c7d0b4501.mp4

**Comment by OliBomby** [comment]
This is caused by the same thing that caused your other issue. You need to update to the latest version of mapping tools which is 1.10.2. I've just updated master branch so you can get it. I think you compiled the program yourself so just fetch the new changes and recompile it.

**Comment by brickyosu** [comment]
> This is caused by the same thing that caused your other issue. You need to update to the latest version of mapping tools which is 1.10.2. I've just updated master branch so you can get it. I think you compiled the program yourself so just fetch the new changes and recompile it.

i dotnet published it tho

**Comment by OliBomby** [comment]
That's the same thing as compiling the program.
