### ISSUE TITLE
[Feature Request] Cleaning slider-notelock

### ISSUE THREAD

**Issue by marcus-wrong** [OliBomby/Mapping_Tools#173]
Haven't seen this documented anywhere and only recently learnt about it myself.

When having doubletap circle+slider on the exact same time, slider-notelock can happen if the circle is the second object instead of the first. What this means is that when hitting the object like a regular doubletap, the slider registers but the circle will always miss. This phenomenon can be observed either in the .osu file (the circle will be on the line after the slider), or the editor.

1. Good (slider slightly raised)
![image](https://user-images.githubusercontent.com/29350765/166190815-c6b811ee-ff34-4364-947e-277d5ad945c2.png)

3. Bad (slider appears normal)
![image](https://user-images.githubusercontent.com/29350765/166190821-8c32a602-0d6a-42b8-b18d-c1baf0a802cc.png)

Usually, fixing it can be simple as just dragging the objects around in the timeline or CTRL+Ging some stuff until you get the desired slider on the timeline. But in cases with Sliderator, dragging the slider isn't so easy anymore as it can occasionally break the slider or even crash the game. Not to mention the slider is usually snapped 1ms before the normal beat so it can break very easily. Thought this could be a simple automated feature considering there is support for Auto-fail detection in 2B maps already! 

Sorry if it has already been mentioned anywhere or is already a feature lol.

**Comment by OliBomby** [comment]
This is a pretty interesting phenomenon that I haven't heard of before. I think I can add this to Map Cleaner without much of a problem.

Should I call this 'Fix 2B doubletaps' or is there a better name.

**Comment by marcus-wrong** [comment]
Not sure if there's a proper name for it but when it was explained to me it was called slidernotelock. I think your suggested description is fine, since the people using it would most likely know what it is referring to anyway.
