### ISSUE TITLE
[Feature Request] Remove ComboX text in Combo Colour Studio

### ISSUE THREAD

**Issue by marcus-wrong** [OliBomby/Mapping_Tools#175]
## Description
Remove ComboX text in Combo Colour Studio when changing combo colours on selected colour point. 

![image](https://user-images.githubusercontent.com/29350765/177293679-e046d649-7a0f-409e-bb9a-5d717f63aa86.png)

**vs**

![image](https://user-images.githubusercontent.com/29350765/177294297-53d7cf6f-52df-4b83-b125-032329c66de4.png)

## Motivation
Not sure if it's a bugfix or a feature. Unless there's something I'm not aware of, the numbering for Combo is pretty redundant considering they are already sorted in order and the names ComboX have no particular usefulness in terms of colorhaxing (there should be sufficient contrast between the colours used anyway to differentiate them). The amount of horizontal space it starts to take for longer colorhax chains makes it much clunkier to use. 

Also would be cool if we could duplicate colour points.

**Comment by OliBomby** [comment]
Good point. I'll add this to the list.
