### ISSUE TITLE
sliderator "import sliders" not working

### ISSUE THREAD

**Issue by naminened** [OliBomby/Mapping_Tools#177]
I select a slider with the current beatmap loaded and saved, press "Import sliders" and nothing happens..?
Help please!

**Comment by naminened** [comment]
uhhh

**Comment by OliBomby** [comment]
Make sure you use the import mode that says 'selected' and select a slider in the editor. Pressing import should work or give some error.
If that doesnt work try another import mode like 'time'. For 'time' you need to copy and paste the selected sliders in the time code field so you have a timestamp there. Also make sure you have set the right current beatmap.

**Comment by naminened** [comment]
its on select, doesnt work. i might try the "time" thing but it is kinda complicated

**Comment by naminened** [comment]
> Make sure you use the import mode that says 'selected' and select a slider in the editor. Pressing import should work or give some error. If that doesnt work try another import mode like 'time'. For 'time' you need to copy and paste the selected sliders in the time code field so you have a timestamp there. Also make sure you have set the right current beatmap.

it also says "could not find the part of the path [my map .osu path] " im confused

**Comment by naminened** [comment]
> Make sure you use the import mode that says 'selected' and select a slider in the editor. Pressing import should work or give some error. If that doesnt work try another import mode like 'time'. For 'time' you need to copy and paste the selected sliders in the time code field so you have a timestamp there. Also make sure you have set the right current beatmap.

it says the map doesnt exist, even though it does

**Comment by OliBomby** [comment]
What you can try doing is re-select the beatmap with File > Open beatmap. This will open an explorer window in which you can select your beatmap file.

The option of File > Open current beatmap might be broken, maybe because the path to your songs folder is incorrect in the Preferences of Mapping Tools.

**Comment by naminened** [comment]
it still doesnt work :(

**Comment by naminened** [comment]
how do i get the logs

**Comment by OliBomby** [comment]
Can you make a video of the problem, showing selecting the beatmap and using the sliderator import function. Then i might know whats going on

**Comment by naminened** [comment]
https://streamable.com/thyzeu

**Comment by naminened** [comment]
sorry for the wait, screen recording problems

**Comment by naminened** [comment]
i also tried reinstalling osu, reinstalling mapping tools and it wont work

**Comment by OliBomby** [comment]
The problem is that your songs folder path is configured incorrectly in mapping tools. It thinks your songs folder is in AppData but your songs folder is actually at `C:\osu!\Songs`. Go to the Preferences page in mapping tools to fix this.

**Comment by naminened** [comment]
OHHHH
