### ISSUE TITLE
How can i fix that error? 

### ISSUE THREAD

**Issue by Gokurotto35** [OliBomby/Mapping_Tools#180]
![image](https://user-images.githubusercontent.com/97704221/187006070-68b7eda4-c89a-42dc-8ce6-c385eb4d6389.png)

**Comment by OliBomby** [comment]
I assume something is wrong with your input, but you didn't share that. It would help a lot if you shared a screenshot of the whole Sliderator tool so I can see your config and also tell me all the steps you took before you encountered this error.
