### ISSUE TITLE
[Feature Request] Hitsound preview helper presets

### ISSUE THREAD

**Issue by joestarrr69** [OliBomby/Mapping_Tools#182]
I hitsound anime and metal stuff and i use multiple different samples for each

![image](https://user-images.githubusercontent.com/116952277/198830024-a62e7352-2b47-451e-90de-d2716349836f.png)

It can be cumbersome to manually change each sample and configure the sampleset and the other stuff. I think a preset feature for these settings would help, tho honestly its just for my convenience.

**Comment by OliBomby** [comment]
Have you tried using the Project menu to save and load configurations?

**Comment by joestarrr69** [comment]
damn i thought the project tab was for stuff in hitsound diff thank you sir olibomby
