### ISSUE TITLE
[Feature Request] Rhythm Guide LN in Mania

### ISSUE THREAD

**Issue by marcus-wrong** [OliBomby/Mapping_Tools#190]
## Prerequisites

- [x] I have checked the [Trello](https://trello.com/b/iTmmw3eP/mapping-tools) and confirmed that the feature is not already planned

## Description
For Rhythm Guide in Mania, add an option to convert sliders into long notes (LNs) so that sliderends, sliderbodies and repeats (passive objects) can be tracked. Alternatively, split the passive objects into a different mania column. 

## Motivation
As it stands, hitsounding in Hitsound Preview Helper (HSP) is not entirely intuitive when using Rhythm Guide since passive objects are interpreted as circles/notes as well. Differentiating between active and passive objects makes hitsounding using HSP much more fluid since there isn't a need to switch back to the original map to check the original rhythm.

**Comment by OliBomby** [comment]
Fair enough
