### ISSUE TITLE
Color Picker for Metadata Manager doesn't work well

### ISSUE THREAD

**Issue by marcus-wrong** [OliBomby/Mapping_Tools#192]
## Prerequisites

- [x] I have read the [Mapping Tools FAQ](https://mappingtools.github.io/faq)

## Environment

**OS version**:  Win11

**Mapping Tools version**:  1.12.2.0

## Description
Color picker for metadata manager doesn't haven't enough vertical space to adjust lightness/brightness values. Tried changing window size etc. and the little gradient box remained the same size.
![image](https://user-images.githubusercontent.com/29350765/214209571-2332798a-7b78-465d-8c0b-0a5a9e0627c5.png)

**Comment by OliBomby** [comment]
yep this is a problem
