### ISSUE TITLE
[Feature Request] Exportable Pattern Gallery

### ISSUE THREAD

**Issue by artrixdotdev** [OliBomby/Mapping_Tools#193]
## Prerequisites

- [x] I have checked the [Trello](https://trello.com/b/iTmmw3eP/mapping-tools) and confirmed that the feature is not already planned

## Description
This feature request is for the addition of an exportable pattern gallery for osu in the Mapping Tools app. Currently, the app's pattern gallery only allows users to browse and select patterns for use in their mapping projects within the app. This feature would enable users to export their custom patterns and import patterns created by others, allowing for a more collaborative and diverse mapping community.

## Motivation
The motivation for this feature is to enhance the functionality of the Mapping Tools app for osu by providing users with a way to share their custom patterns with others. The addition of an exportable pattern gallery would enable osu players and mappers to create more diverse and engaging mapping projects by allowing them to save time and effort when creating new patterns.

With the ability to export and share custom patterns, the osu mapping community would be able to collaborate and share their creativity, leading to a more dynamic and engaging experience for all users. An exportable pattern gallery would provide a convenient way for users to share their custom patterns with others, encouraging the community to work together to create innovative and exciting mapping projects.

**Comment by OliBomby** [comment]
![NVIDIA_Share_qEDoT7dmMi](https://user-images.githubusercontent.com/17460441/218899993-c1d1a860-7a85-4fb2-8778-3d3ef8a7b9c8.png)
