### ISSUE TITLE
[Feature Request] Hitsound copier different "only defined behavior

### ISSUE THREAD

**Issue by hikizisa** [OliBomby/Mapping_Tools#201]
## Prerequisites

- [x] I have checked the [Trello](https://trello.com/b/iTmmw3eP/mapping-tools) and confirmed that the feature is not already planned

## Description
A clear and concise description of what the feature is

## Motivation
Outline the motivation for this feature and why it should be implemented. Has it been requested by a large amount of users? Does it address a problem that currently can't, or is difficult to, be fixed?

**Comment by OliBomby** [comment]
![Mapping_Tools_cxnfFdfwi8](https://github.com/OliBomby/Mapping_Tools/assets/17460441/7c1661b5-6305-469a-b062-b48c1a8c53ab)
This tooltip is a clear and concise description of the feature.
