### ISSUE TITLE
Add selected hit object to pattern gallery error

### ISSUE THREAD

**Issue by aerotracker** [OliBomby/Mapping_Tools#203]
## Prerequisites

- [x] I have read the [Mapping Tools FAQ](https://mappingtools.github.io/faq)

## Environment

**OS version**: Windows 11

**Mapping Tools version**: 1.12.14.0

## Description
Error when tried to add pattern from selected hit object,
Issue seems only persist my own beatmap that has already been submitted,
non submitted didn't show any error during the process

### Reproduction

1. Open your own submitted Map in editor
2. In Editor, Select hit object that going to be added to pattern gallery
3. In Mapping Tools, Click add selected hit object to pattern gallery 

### Screenshots/Recordings
![image](https://github.com/OliBomby/Mapping_Tools/assets/62961771/4d46e531-3b3a-4f07-9897-8827cd4af64d)
![image](https://github.com/OliBomby/Mapping_Tools/assets/62961771/2f2eb2c9-1515-45cf-b14e-c25a66932b01)

## Additional context
- Only happen on 1.12.14 releases
- Beatmap path somehow has additional markup (the [bold0;size20]). 
- Same issue seems to also appear on beatmap created by other creator, if File -> Open Current Beatmap not initiated for the first time after opening mappin tools
- File -> Open Current Beatmap doesn't resolve the issue with beatmap created by myself
- On Previous releases, not doing the File -> Open Current Beatmap right after opening Mapping tools or changing the map in view won't cause any error
- Tested on 1.12.12 and 1.12.13, both don't show any error even without doing the File -> Open Current Beatmap

**Comment by OliBomby** [comment]
I've known about this error occuring randomly for some users, but never been able to recreate it.

It's weird how it works on 1.12.13 for you because between that version and 1.12.14 nothing changed in the parts of the program that are responsible for this error. Does the issue persist on your map even after reinstalling 1.12.14?

**Comment by aerotracker** [comment]
issues doesn't persist after reinstalling
i think i need to added further context, so it won't misslead the troubleshooting 
the files were originated from my laptop before i transfer it to my pc and i only copied the folder where the executable located
i didn't copy the folder from the appdata
