### ISSUE TITLE
"Install .NET" prompt does nothing on portable version

### ISSUE THREAD

**Issue by Apis035** [OliBomby/Mapping_Tools#205]
## Prerequisites

- [x] I have read the [Mapping Tools FAQ](https://mappingtools.github.io/faq)

## Environment

**OS version**: Windows 10 22H2
**Mapping Tools version**: 1.12.17.0

## Description

Running Mapping Tools portable on a machine with no .NET 5 installed, MT shows this dialog:
![image](https://github.com/OliBomby/Mapping_Tools/assets/53115851/8799e09d-9bab-44aa-9131-05dc684d983b)
Clicking either "yes" or "no" button does nothing. (e.g. directs into .NET download page, or automatically download and install required .NET for you)

It doesn't even show which .NET version is required (which is .NET 5), as I got confused because I have .NET 6 and .NET 8 installed on my machine. I discovered it later which .NET version is required after installing MT installer version.

**Comment by OliBomby** [comment]
I can't do anything about this dialogue box because it is not a part of mapping tools

**Comment by Apis035** [comment]
Could you at least put the needed .NET version in the readme or download page? Incase if someone else or me in the future -- for example -- reinstalled my PC and I forgot what the needed .NET version is.

**Comment by OliBomby** [comment]
the needed .NET version is already explained on the [installation page](https://mappingtools.github.io/docs/mapping-tools/installation), but I'll add it to the readme too
