### ISSUE TITLE
"Object Refference not set to an instance of an object. " When using the "Import Midi" option for Hitsound Studio

### ISSUE THREAD

**Issue by Coppertine** [OliBomby/Mapping_Tools#26]
The main issue that I can arise is that Mapping Tools does not expect a midi to be loaded to the source path parameter  since it can only accept .osu files.

**Comment by OliBomby** [comment]
The source path field certainly does expect to get a path to a midi file.
It might have to do with the specific midi you're using or how you configured the other settings. 
Can you send a link to your midi and a screenshot of your other options.
You can also test if other midi files do work.

**Comment by Coppertine** [comment]
![image](https://user-images.githubusercontent.com/37494321/62409912-77b46d80-b621-11e9-810c-c686160ee7b5.png)
![image](https://user-images.githubusercontent.com/37494321/62409914-813dd580-b621-11e9-9f9a-fb42ec3bfad7.png)

This is the edited values after creating a blank layer then changing to a midi format. Which does nothing.

**Comment by Coppertine** [comment]
[coppertine_u_owe_me_4_months_of_supp_lol.zip](https://github.com/OliBomby/Mapping_Tools/files/3463576/coppertine_u_owe_me_4_months_of_supp_lol.zip)
And here is the midi

**Comment by OliBomby** [comment]
I instantly see the problem here.
You're supposed to import midi's by clicking on the plus button and then going to the import midi tab. If there was a tutorial you would have known this. Sorry about that ><

Doing it the way you did it could also work but then you'd need to know beforehand what keys and instruments your midi uses. I think there is no key 1 in your midi so it got a null exception. Keys usually go from 40 to 80 ish.

**Comment by Coppertine** [comment]
![image](https://user-images.githubusercontent.com/37494321/62410415-64f16700-b628-11e9-8735-e78c56bcea7f.png)
![image](https://user-images.githubusercontent.com/37494321/62410419-6d49a200-b628-11e9-969a-8807e95402b8.png)
This is what happens when I use the plus button to import the midi

**Comment by OliBomby** [comment]
Okay so i checked it out. Your midi had tempo defined on not track 0 so that was unexpected. I fixed it with the latest pull request, but you'll have to wait for potoofu to make a new build update.
