### ISSUE TITLE
MIDI sounds from SFZ/SF2 samples does not render properly

### ISSUE THREAD

**Issue by Coppertine** [OliBomby/Mapping_Tools#58]
https://cdn.discordapp.com/attachments/525989766743851039/639093834395025410/unknown.png

**Comment by OliBomby** [comment]
ok nice screenshot but it doesnt help me at all

**Comment by OliBomby** [comment]
send me the exact hs studio project and soundfont file

**Comment by Coppertine** [comment]
Ment to be a reminder to fix the issue of spesified sf2's which could be sustains as well.

**Comment by OliBomby** [comment]
bro i dont even know what the issue actually is. It's like you have some sort of weird soundfont which is structured in a shitty way.

**Comment by Coppertine** [comment]
It's from ScubDomino's issue with the hitsounding where either the keys spesifed in the sf2 don't corrolate to the midi or smth?

**Comment by OliBomby** [comment]
fixed in commit "fixed -1 pitch shifts getting ignored"
