### ISSUE TITLE
Suggestion: open the latest opened folder in explorer instead of the "current map" folder in hitsound copier/metadata manager/timing copier

### ISSUE THREAD

**Issue by Ryuusei-Aika** [OliBomby/Mapping_Tools#68]
My wording may be a little bit bad in the title so I'll explain below in detail:

For example, If I want to import metadata from map folder A while the "current map" shows map folder B (could due to I've opened another mapset before because I want to use property transformer etc.), I have to find again A when I want to export metadata to every .osu file in A because when I click the folder icon after the "Export metadata from", it opens B instead of A.

Honestly I think when people want to use hitsound copier, metadata transformer and timing copier they would expect to open the same folder at the very first time when they choose the "from" folder and the "to" folder, so it would be better that when I open A in the "from" section, the tools open A instantly when i click the folder icon after the "to" section.

Generally A and B would not be the same since in my opinion people won't use the "open current beatmap folder" section when they use hitsound copier/metadata manager/timing copier, I believe most of the cases are people want to do the import/export works really quick even without opening osu! (while "open current beatmap" requires your game opened), so I think this change could benifit a lot in terms of efficiency, especially when people have used different tools on different mapset using "open current beatmap" operation and want to use the three tools I've mentioned above in another mapset.

**Comment by OliBomby** [comment]
Yo I remember getting a request to open to the current beatmap's folder, so that's why it's how it's right now. What I get from this suggestion is that there are tools which don't really use the current map, so those should open the file explorer in the folder last file explored. That makes sense.
