### ISSUE TITLE
BetterSave not working on Ctrl+S when im Editor

### ISSUE THREAD

**Issue by MaxKruse** [OliBomby/Mapping_Tools#74]
I only have MappingTools and osu! open, when i try to better save with the ctrl+s override, it gives me 
"The calling thread cannot access this object, because it is in use by another thread". Which could only be osu

**Comment by OliBomby** [comment]
This was an issue with the snackbar message that is supposed to show up when you bettersave. I already fixed it but forgot to make an update.

**Comment by OliBomby** [comment]
I made a new update with the fix.
