### ISSUE TITLE
The Default explorer location is still random-ish (last used by Windows).

### ISSUE THREAD

**Issue by OliBomby** [OliBomby/Mapping_Tools#77]
this doesnt fix #68 for me when im applying hitsounds. the Default explorer location is still random-ish (last used by Windows).

_Originally posted by @MaxKruse in https://github.com/OliBomby/Mapping_Tools/pull/71#issuecomment-570047430_

**Comment by OliBomby** [comment]
@MaxKruse Do you mean the file explorer should open in the last opened folder by Mapping Tools instead of the last opened by windows?

**Comment by MaxKruse** [comment]
i mean it should start in the folder of the current beatmap, as selected by "open current beatmap from osu editor"

**Comment by OliBomby** [comment]
> i mean it should start in the folder of the current beatmap, as selected by "open current beatmap from osu editor"

That's exactly how it used to work previously. I guess people have different preferences so I should make this an option in the preferences.
