### ISSUE TITLE
Hitsound Copier doesn't transfer over slider sounds if a slider has a sound but a sliderstart doesn't

### ISSUE THREAD

**Issue by h3oCharles** [OliBomby/Mapping_Tools#92]
make a slider, put a Clap on it, Clap also sounds on slider start and end

if on a diff that you try to copy sounds to there's a circle on the same timeline, the sound doesn't transfer

**Comment by OliBomby** [comment]
I found the issue. The program didnt read hitsounds from sliders without extras correctly. That is now fixed.
