### ISSUE TITLE
Preview graph of sliderator uses excessive amounts of cpu cycles

### ISSUE THREAD

**Issue by potoofu** [OliBomby/Mapping_Tools#93]
See title ...

On an 8 thread/5ghz cpu just dragging the graph uses up ~20%

Could be an issue of:
- redundant graph draw cycles
- expensive operations for other things than the graph during a draw

It should also be looked into the way a change event refreshes the graph if that refresh is even needed on every event. Could be an input buffer of like 1000ms or smth.

**Comment by OliBomby** [comment]
I'll investigate exactly what happens when you use the graph

**Comment by OliBomby** [comment]
subjective no change
