### ISSUE TITLE
Cutting Edge is broken

### ISSUE THREAD

**Issue by MaxKruse** [OliBomby/Mapping_Tools#98]
This used to work on cutting edge. Since some update (i dont know which exactly), neither the "Open Current Beatmap" nor any functionality based on this works. BetterSave crashes the program.

**Comment by OliBomby** [comment]
I just did some basic testing and for me 'Open Current Beatmap' is working on cutting edge. BetterSave does indeed crash the program. I'll at least fix that.
As long as 'Open Current Beatmap' is working for me, I can't really debug it.

**Comment by OliBomby** [comment]
I fixed BetterSave being able to crash mapping tools.
